unitTestList = [
    {'cipher': 'Slma vm aol uvyt',
     'shift':7,
     'decrypted':'Left of the norm'},
    {'cipher': 'Ymj xyfwx fwj gjfzynkzq ytsnlmy.',
     'shift':5,
     'decrypted':'The stars are beautiful tonight.'},
    {'cipher': 'T wzgp dzwgtyr afkkwpd ty Ajeszy.',
     'shift':11,
     'decrypted':'I love solving puzzles in Python.'},
    {'cipher': 'Gdqjhu lv dssurdfklqj iurp wkh hdvw.',
     'shift':3,
     'decrypted':'Danger is approaching from the east.'},
    {'cipher': 'Ol tbza uva ruvd vby wshu.',
     'shift':7,
     'decrypted':'He must not know our plan.'},
    {'cipher': 'Max vehvd lmkbdxl mpxeox tm ghhg.',
     'shift':19,
     'decrypted':'The clock strikes twelve at noon.'},
    {'cipher': 'Arire sbetrg gb purpx gur ybtf.',
     'shift':13,
     'decrypted':'Never forget to check the logs.'},
    {'cipher': 'Myno vsuo k gsjkbn.',
     'shift':10,
     'decrypted':'Code like a wizard.'},
    {'cipher': 'Epp yrmxw vitsvx xs fewi mqqihmexipc.',
     'shift':4,
     'decrypted':'All units report to base immediately.'},
    {'cipher': 'Tcrgneixdc rpc egditri bthhpvth.',
     'shift':15,
     'decrypted':'Encryption can protect messages.'},
    {'cipher': 'Eibkp bpm pwzqhwv nwz ivg uwdmumvb.',
     'shift':8,
     'decrypted':'Watch the horizon for any movement.'},
    {'cipher': '“Fhewhuii,” ixu iqyt, “yid’j qbmqoi erlyeki. Iecujycui yj vuubi byau oek’hu ijqdtydw ijybb--ulud ibytydw rqsamqht--rkj jxud, edu tqo, oek beea kf qdt huqbypu xem vqh oek’lu secu.”',
     'shift':16,
     'decrypted':'“Progress,” she said, “isn’t always obvious. Sometimes it feels like you’re standing still—even sliding backward—but then, one day, you look up and realize how far you’ve come.”'},
    {'cipher': 'Kvsb hvs righ gshhzsg, kwzz ks ps dfcir ct kvoh ks piwzh? Cf kwzz ks fsufsh hvs acasbhg ks koghsr dfshsbrwbu ks vor tcfsjsf?',
     'shift':14,
     'decrypted':'When the dust settles, will we be proud of what we built? Or will we regret the moments we wasted pretending we had forever?'},
    ]